/**
 * server/lib/abandonment.js — Phase 2 Step 6: abandonment + abuse-monitoring sweep.
 *
 * Deletes pending accounts that never completed onboarding within the abandonment
 * window (policies.md §6 — default 30 days), releasing their system-generated username,
 * and records a de-identified HMAC of the email in email_hash_abuse so repeat-abandon /
 * signup-spam stays detectable without retaining deleted-user PII.
 *
 * Why this lives in Node (not pg_cron / pure SQL): the abuse hash is a KEYED HMAC whose
 * pepper must never enter Postgres (decisions.md 2026-06-10). So the hash is computed
 * here with node:crypto; Postgres only ever sees the hash, never the pepper or plaintext.
 *
 * Flow per account (record-then-delete, so we never destroy an account whose hash failed
 * to persist):
 *   1. list_abandoned_pending_accounts(interval)  → {account_id, tenant_id,
 *      canonical_email, username_source}                         (RPC, mig 012)
 *   2. guard: skip anything not username_source='system_generated' (defensive — never
 *      release a user-chosen / shared handle via this path)
 *   3. HMAC-SHA256(canonical_email, pepper) → hex; record_abandoned_email_hash(...)  (RPC)
 *   4. auth.admin.deleteUser(account_id) → ON DELETE CASCADE drops profiles +
 *      account_identifiers (username + email) + account_settings (mig 007). The username
 *      row vanishing IS the release — no separate RPC.
 *
 * Identity is injected via config (not read from module-level env) so the same function
 * runs from the Vercel handler (prod/preview env) and the staging gate (STAGING_* env)
 * without ambiguity. NEVER expose the service-role key or pepper to the browser.
 *
 * Ref: policies.md §6 · decisions.md 2026-06-10 · migration 012 · architecture.md §7
 */

import { createHmac } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

/**
 * @typedef {Object} AbandonmentConfig
 * @property {string}  [supabaseUrl]      Supabase project URL (required unless supabaseClient given)
 * @property {string}  [serviceRoleKey]   service_role key (required unless supabaseClient given)
 * @property {object}  [supabaseClient]   pre-built service-role client (tests may inject one)
 * @property {string}  [pepper]           HMAC pepper; required unless dryRun
 * @property {number}  [keyVersion=1]     pepper key version stamped on each hash row
 * @property {number}  [maxAgeDays=30]    abandonment window in days (policies.md §6)
 * @property {boolean} [dryRun=false]     when true: scan + log only, no hash writes, no deletes
 * @property {object}  [logger=console]   logger with .info/.warn/.error
 */

/**
 * Run one abandonment sweep across ALL tenants.
 * @param {AbandonmentConfig} config
 * @returns {Promise<{scanned:number, deleted:number, hashed:number, skipped:number,
 *                     errors:number, dryRun:boolean, maxAgeDays:number, keyVersion:number}>}
 */
export async function runAbandonmentSweep(config = {}) {
  const {
    supabaseUrl,
    serviceRoleKey,
    supabaseClient,
    pepper,
    keyVersion = 1,
    maxAgeDays = 30,
    dryRun = false,
    logger = console,
  } = config;

  const svc =
    supabaseClient ||
    (() => {
      if (!supabaseUrl || !serviceRoleKey) {
        throw new Error(
          'runAbandonmentSweep: supabaseUrl + serviceRoleKey (or supabaseClient) are required',
        );
      }
      return createClient(supabaseUrl, serviceRoleKey, {
        auth: { persistSession: false, autoRefreshToken: false },
      });
    })();

  // A destructive sweep must never run without the hash key — otherwise we'd delete
  // accounts and silently lose the abuse signal. Dry runs may omit it.
  if (!dryRun && !pepper) {
    throw new Error('runAbandonmentSweep: pepper is required for a live (non-dry-run) sweep');
  }
  if (!Number.isInteger(keyVersion) || keyVersion < 1) {
    throw new Error(`runAbandonmentSweep: keyVersion must be a positive integer (got ${keyVersion})`);
  }

  const summary = {
    scanned: 0, deleted: 0, hashed: 0, skipped: 0, errors: 0,
    dryRun, maxAgeDays, keyVersion,
  };

  const { data: accounts, error: listErr } = await svc.rpc('list_abandoned_pending_accounts', {
    p_max_age: `${maxAgeDays} days`,
  });
  if (listErr) {
    throw new Error(`list_abandoned_pending_accounts failed: ${listErr.message}`);
  }

  summary.scanned = accounts?.length ?? 0;
  logger.info(
    `[abandonment] scanned ${summary.scanned} pending account(s) older than ${maxAgeDays}d` +
      (dryRun ? ' (DRY RUN — no writes/deletes)' : ''),
  );

  for (const acct of accounts ?? []) {
    const { account_id, tenant_id, canonical_email, username_source } = acct;

    // Defensive guard: every pending account is system_generated by construction, and the
    // policy releases ONLY the system-generated handle of an abandoned signup. If we ever
    // see anything else here, skip rather than risk releasing a user-chosen/shared handle.
    if (username_source !== 'system_generated') {
      summary.skipped += 1;
      logger.warn(
        `[abandonment] skip ${account_id}: username_source='${username_source}' (not system_generated)`,
      );
      continue;
    }

    try {
      // 1. Record the abuse hash BEFORE deleting, so an account is never destroyed with
      //    its abuse signal unrecorded. Skip (with a warning) only if there's no email.
      if (canonical_email) {
        const emailHashHex = createHmac('sha256', pepper || '')
          .update(canonical_email, 'utf8')
          .digest('hex');

        if (!dryRun) {
          const { error: hashErr } = await svc.rpc('record_abandoned_email_hash', {
            p_tenant_id: tenant_id,
            p_email_hash_hex: emailHashHex,
            p_key_version: keyVersion,
          });
          if (hashErr) {
            throw new Error(`record_abandoned_email_hash failed: ${hashErr.message}`);
          }
        }
        summary.hashed += 1;
      } else {
        logger.warn(`[abandonment] ${account_id}: no active email identifier — deleting without hash`);
      }

      // 2. Delete the auth.users row → cascade releases username + email + settings.
      if (!dryRun) {
        const { error: delErr } = await svc.auth.admin.deleteUser(account_id);
        if (delErr) {
          throw new Error(`admin.deleteUser failed: ${delErr.message}`);
        }
      }
      summary.deleted += 1;
    } catch (err) {
      summary.errors += 1;
      logger.error(`[abandonment] error processing ${account_id}: ${err.message}`);
      // Continue the sweep; one bad account shouldn't abort the rest.
    }
  }

  logger.info(
    `[abandonment] done — deleted=${summary.deleted} hashed=${summary.hashed} ` +
      `skipped=${summary.skipped} errors=${summary.errors}${dryRun ? ' (dry run)' : ''}`,
  );
  return summary;
}
